#!/bin/sh
set -eu

# ----------------------------------------------------------------------------------------------------------------------


# Run Entrypoint and pass CMD to it (Don't forget exec)
exec base-entrypoint "${@}"