#!/bin/sh
set -eu

# ----------------------------------------------------------------------------------------------------------------------

``# Run Composer Install ( --no-scripts to avoid time consuming cache clear)
composer install --no-scripts

# Install Public Assets if they're not generated.
test -d "public/bundles" || composer run auto-scripts

composer check-platform-reqs  && \
post-build

# Run Entrypoint and pass CMD to it (Don't forget exec)
exec entrypoint-base "${@}"