#!/bin/sh
set -eu

# Run Envsubst on .env to expand embedded Env Variables
for f in $(find . -name ".env*"); do cat $f | envsubst "$(env | sed -e 's/=.*//' -e 's/^/\$/g')" > "$f"; done

# ----------------------------------------------------------------------------------------------------------------------

# Run Entrypoint and pass CMD to it (Don't forget exec)
exec entrypoint-base "${@}"