#!/bin/sh
set -eu

# --------------------------------------------------------------------------------------------------------------------

# Run custom ad-hoc pre-run script
echo "► Running custom pre-run script..."
pre-run
echo "✔ Successful"

# ----------------------------------------------------------------------------------------------------------------------

# Run Dockerfile's CMD (default: $> php-fpm )
echo "► Starting... cmd: ${@}"
exec tini -- "${@}"