#!/bin/sh
set -eu

# ----------------------------------------------------------------------------------------------------------------------

echo "Checking if 'vendor' folder exists..."
if [ -d "vendor" ]; then
  echo "'Vendor' Folder exists, Skipping running Composer Install."
  echo "To install new package, either run 'composer install' from inside the container via 'exec', or remove the vendor folder all together."
else
  echo "Vendor Folder does not exist, running composer install..."
  composer install -n
fi

# Run Entrypoint and pass CMD to it (Don't forget exec)
exec entrypoint-base "${@}"