#!/bin/sh
set -eu

# ----------------------------------------------------------------------------------------------------------------------

# Run Inside a subshell to not expose .env to entrypoint.
(
  # Load .env and .env.<APP_ENV> into script (won't overwrite OS env vars.)
  set -a
      env_overwrite=./.env.${APP_ENV-prod}
      export -p >> /tmp/envsrc && if [ -f "./.env" ]; then . ./.env; fi && if [ -f "${env_overwrite}" ]; then . $env_overwrite; fi && . /tmp/envsrc \
      && rm /tmp/envsrc && unset env_overwrite
  set +a

  # ----------------------------------------------------------------------------------------------------------------------

  # Add Prod Specific Entrypoints Here.

)


# Run Entrypoint and pass CMD to it (Don't forget exec)
exec base-entrypoint "${@}"