#!/bin/sh
set -eu

# ----------------------------------------------------------------------------------------------------------------------

echo "► Starting Production Entrypoint..."

# ----------------------------------------------------------------------------------------------------------------------

## Run Envsubst on .env to expand embedded Env Variables
#echo "► Expanding Dotenv files with Environment Variables..."
#for f in $(find . -name ".env*"); do cat $f | envsubst "$(env | sed -e 's/=.*//' -e 's/^/\$/g')" > "$f"; done

# ----------------------------------------------------------------------------------------------------------------------

# Run Entrypoint and pass CMD to it (Don't forget exec)
exec entrypoint-base "${@}"
