#!/bin/sh
set -eu

# Scripts that will run composer install and composer post install command.
# And before running the container main command/process.

# This script working dir is application's directory, and all ENV variables from .env and OS are available here
# using ${ENV_NAME} with defaults taken from .env and .env.<env>
#
# Ex:
#   { echo ${DATABASE_URL};  echo "stdin input"; } | vendor/bin/<script that need stdin input>


# Put Custom Ad-hoc scripts below:

echo "hello-world" >> /tmp/iran.txt