#!/bin/sh
set -eu

# Permissions for var directory
chown -R www-data:www-data var

# Install Dependencies ( --no-scripts here as scripts ar run in main entrypoint )
echo "Running Composer Install..."
composer install --prefer-dist --no-interaction --no-scripts

# Checks that PHP and extensions versions match the platform requirements of the installed packages.
echo "Checking Platform requirements"
composer check-platform-reqs