#!/bin/sh
set -e

# Dev entry point does steps that is done in prod image, only that it does it at
# container runtime not image build time, as dev container expects the code to be
# mounted.
docker-dev-install

echo "Starting..."
exec docker-fpm-entrypoint