name: Publish Container Images

on:
  schedule:
    - cron: '35 7 * * *'
  push:
    branches:
      - main
      - master
    tags: ['*.*.*']
  pull_request:
    branches:
      - main
      - master

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract app metadata
        id: meta-app
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app

      - name: Build and push app image
        id: build-and-push-app
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          target: app
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}

      - name: Extract app-dev metadata
        id: meta-app-dev
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app-dev

      - name: Build and push app image
        id: build-and-push-app-dev
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          target: app-dev
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-app-dev.outputs.tags }}
          labels: ${{ steps.meta-app-dev.outputs.labels }}

      - name: Extract web metadata
        id: meta-web
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/web

      - name: Build and push web image
        id: build-and-push-web
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          target: web
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}

      - name: Extract web-dev metadata
        id: meta-web-dev
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/web-dev

      - name: Build and push web-dev image
        id: build-and-push-web-dev
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          target: web-dev
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-web-dev.outputs.tags }}
          labels: ${{ steps.meta-web-dev.outputs.labels }}
